// Generated by purs bundle 0.12.0
var PS = {};
(function(exports) {exports.exportOne = function () {
    console.log('I am export One!')
  }
})(PS["Main"] = PS["Main"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Main"];
  var Effect = PS["Effect"];
  var Prelude = PS["Prelude"];                 
  var main = $foreign.exportOne;
  exports["main"] = main;
})(PS["Main"] = PS["Main"] || {});
PS["Main"].main();